name: capstone
channels:
  - defaults
dependencies:
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - blas=1.0
  - bleach=3.3.1
  - certifi=2021.5.30
  - cffi=1.14.6
  - click=8.0.1
  - colorama=0.4.4
  - contextvars=2.4
  - dataclasses=0.8
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - idna=3.2
  - immutables=0.15
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - ipykernel=5.3.4
  - ipython=6.1.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.6.1
  - libsodium=1.0.18
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.0.1
  - mistune=0.8.4
  - mkl=2017.0.3
  - msys2-conda-epoch=20160418
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - nltk=3.6.2
  - notebook=6.4.0
  - numpy=1.13.1
  - packaging=21.0
  - pandas=0.20.3
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pickleshare=0.7.5
  - pip=21.1.3
  - prometheus_client=0.11.0
  - prompt_toolkit=1.0.15
  - pycparser=2.20
  - pygments=2.9.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - python=3.6.13
  - python-dateutil=2.8.2
  - pytz=2021.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=20.0.0
  - regex=2021.7.6
  - requests=2.14.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - simplegeneric=0.8.1
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.36.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tornado=6.1
  - tqdm=4.61.2
  - traitlets=4.3.3
  - typing_extensions=3.10.0.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.3
  - zipp=3.5.0
